// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ohlc.proto
#ifndef GRPC_ohlc_2eproto__INCLUDED
#define GRPC_ohlc_2eproto__INCLUDED

#include "ohlc.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace ohlc {

class OHLCConsumerService final {
 public:
  static constexpr char const* service_full_name() {
    return "ohlc.OHLCConsumerService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SendOHLC(::grpc::ClientContext* context, const ::ohlc::OHLC& request, ::ohlc::SendOHLCResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ohlc::SendOHLCResponse>> AsyncSendOHLC(::grpc::ClientContext* context, const ::ohlc::OHLC& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ohlc::SendOHLCResponse>>(AsyncSendOHLCRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ohlc::SendOHLCResponse>> PrepareAsyncSendOHLC(::grpc::ClientContext* context, const ::ohlc::OHLC& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ohlc::SendOHLCResponse>>(PrepareAsyncSendOHLCRaw(context, request, cq));
    }
    virtual ::grpc::Status GetOHLC(::grpc::ClientContext* context, const ::ohlc::StockRequest& request, ::ohlc::OHLC* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ohlc::OHLC>> AsyncGetOHLC(::grpc::ClientContext* context, const ::ohlc::StockRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ohlc::OHLC>>(AsyncGetOHLCRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ohlc::OHLC>> PrepareAsyncGetOHLC(::grpc::ClientContext* context, const ::ohlc::StockRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ohlc::OHLC>>(PrepareAsyncGetOHLCRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SendOHLC(::grpc::ClientContext* context, const ::ohlc::OHLC* request, ::ohlc::SendOHLCResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendOHLC(::grpc::ClientContext* context, const ::ohlc::OHLC* request, ::ohlc::SendOHLCResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetOHLC(::grpc::ClientContext* context, const ::ohlc::StockRequest* request, ::ohlc::OHLC* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetOHLC(::grpc::ClientContext* context, const ::ohlc::StockRequest* request, ::ohlc::OHLC* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ohlc::SendOHLCResponse>* AsyncSendOHLCRaw(::grpc::ClientContext* context, const ::ohlc::OHLC& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ohlc::SendOHLCResponse>* PrepareAsyncSendOHLCRaw(::grpc::ClientContext* context, const ::ohlc::OHLC& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ohlc::OHLC>* AsyncGetOHLCRaw(::grpc::ClientContext* context, const ::ohlc::StockRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ohlc::OHLC>* PrepareAsyncGetOHLCRaw(::grpc::ClientContext* context, const ::ohlc::StockRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SendOHLC(::grpc::ClientContext* context, const ::ohlc::OHLC& request, ::ohlc::SendOHLCResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ohlc::SendOHLCResponse>> AsyncSendOHLC(::grpc::ClientContext* context, const ::ohlc::OHLC& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ohlc::SendOHLCResponse>>(AsyncSendOHLCRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ohlc::SendOHLCResponse>> PrepareAsyncSendOHLC(::grpc::ClientContext* context, const ::ohlc::OHLC& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ohlc::SendOHLCResponse>>(PrepareAsyncSendOHLCRaw(context, request, cq));
    }
    ::grpc::Status GetOHLC(::grpc::ClientContext* context, const ::ohlc::StockRequest& request, ::ohlc::OHLC* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ohlc::OHLC>> AsyncGetOHLC(::grpc::ClientContext* context, const ::ohlc::StockRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ohlc::OHLC>>(AsyncGetOHLCRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ohlc::OHLC>> PrepareAsyncGetOHLC(::grpc::ClientContext* context, const ::ohlc::StockRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ohlc::OHLC>>(PrepareAsyncGetOHLCRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SendOHLC(::grpc::ClientContext* context, const ::ohlc::OHLC* request, ::ohlc::SendOHLCResponse* response, std::function<void(::grpc::Status)>) override;
      void SendOHLC(::grpc::ClientContext* context, const ::ohlc::OHLC* request, ::ohlc::SendOHLCResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetOHLC(::grpc::ClientContext* context, const ::ohlc::StockRequest* request, ::ohlc::OHLC* response, std::function<void(::grpc::Status)>) override;
      void GetOHLC(::grpc::ClientContext* context, const ::ohlc::StockRequest* request, ::ohlc::OHLC* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ohlc::SendOHLCResponse>* AsyncSendOHLCRaw(::grpc::ClientContext* context, const ::ohlc::OHLC& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ohlc::SendOHLCResponse>* PrepareAsyncSendOHLCRaw(::grpc::ClientContext* context, const ::ohlc::OHLC& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ohlc::OHLC>* AsyncGetOHLCRaw(::grpc::ClientContext* context, const ::ohlc::StockRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ohlc::OHLC>* PrepareAsyncGetOHLCRaw(::grpc::ClientContext* context, const ::ohlc::StockRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SendOHLC_;
    const ::grpc::internal::RpcMethod rpcmethod_GetOHLC_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SendOHLC(::grpc::ServerContext* context, const ::ohlc::OHLC* request, ::ohlc::SendOHLCResponse* response);
    virtual ::grpc::Status GetOHLC(::grpc::ServerContext* context, const ::ohlc::StockRequest* request, ::ohlc::OHLC* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SendOHLC : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendOHLC() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SendOHLC() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendOHLC(::grpc::ServerContext* /*context*/, const ::ohlc::OHLC* /*request*/, ::ohlc::SendOHLCResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendOHLC(::grpc::ServerContext* context, ::ohlc::OHLC* request, ::grpc::ServerAsyncResponseWriter< ::ohlc::SendOHLCResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetOHLC : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetOHLC() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetOHLC() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetOHLC(::grpc::ServerContext* /*context*/, const ::ohlc::StockRequest* /*request*/, ::ohlc::OHLC* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetOHLC(::grpc::ServerContext* context, ::ohlc::StockRequest* request, ::grpc::ServerAsyncResponseWriter< ::ohlc::OHLC>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SendOHLC<WithAsyncMethod_GetOHLC<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SendOHLC : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendOHLC() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::ohlc::OHLC, ::ohlc::SendOHLCResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ohlc::OHLC* request, ::ohlc::SendOHLCResponse* response) { return this->SendOHLC(context, request, response); }));}
    void SetMessageAllocatorFor_SendOHLC(
        ::grpc::MessageAllocator< ::ohlc::OHLC, ::ohlc::SendOHLCResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ohlc::OHLC, ::ohlc::SendOHLCResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SendOHLC() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendOHLC(::grpc::ServerContext* /*context*/, const ::ohlc::OHLC* /*request*/, ::ohlc::SendOHLCResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendOHLC(
      ::grpc::CallbackServerContext* /*context*/, const ::ohlc::OHLC* /*request*/, ::ohlc::SendOHLCResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetOHLC : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetOHLC() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::ohlc::StockRequest, ::ohlc::OHLC>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ohlc::StockRequest* request, ::ohlc::OHLC* response) { return this->GetOHLC(context, request, response); }));}
    void SetMessageAllocatorFor_GetOHLC(
        ::grpc::MessageAllocator< ::ohlc::StockRequest, ::ohlc::OHLC>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ohlc::StockRequest, ::ohlc::OHLC>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetOHLC() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetOHLC(::grpc::ServerContext* /*context*/, const ::ohlc::StockRequest* /*request*/, ::ohlc::OHLC* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetOHLC(
      ::grpc::CallbackServerContext* /*context*/, const ::ohlc::StockRequest* /*request*/, ::ohlc::OHLC* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SendOHLC<WithCallbackMethod_GetOHLC<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SendOHLC : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendOHLC() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SendOHLC() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendOHLC(::grpc::ServerContext* /*context*/, const ::ohlc::OHLC* /*request*/, ::ohlc::SendOHLCResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetOHLC : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetOHLC() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetOHLC() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetOHLC(::grpc::ServerContext* /*context*/, const ::ohlc::StockRequest* /*request*/, ::ohlc::OHLC* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendOHLC : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendOHLC() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SendOHLC() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendOHLC(::grpc::ServerContext* /*context*/, const ::ohlc::OHLC* /*request*/, ::ohlc::SendOHLCResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendOHLC(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetOHLC : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetOHLC() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetOHLC() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetOHLC(::grpc::ServerContext* /*context*/, const ::ohlc::StockRequest* /*request*/, ::ohlc::OHLC* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetOHLC(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendOHLC : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendOHLC() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SendOHLC(context, request, response); }));
    }
    ~WithRawCallbackMethod_SendOHLC() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendOHLC(::grpc::ServerContext* /*context*/, const ::ohlc::OHLC* /*request*/, ::ohlc::SendOHLCResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendOHLC(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetOHLC : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetOHLC() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetOHLC(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetOHLC() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetOHLC(::grpc::ServerContext* /*context*/, const ::ohlc::StockRequest* /*request*/, ::ohlc::OHLC* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetOHLC(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendOHLC : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendOHLC() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ohlc::OHLC, ::ohlc::SendOHLCResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ohlc::OHLC, ::ohlc::SendOHLCResponse>* streamer) {
                       return this->StreamedSendOHLC(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SendOHLC() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendOHLC(::grpc::ServerContext* /*context*/, const ::ohlc::OHLC* /*request*/, ::ohlc::SendOHLCResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendOHLC(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ohlc::OHLC,::ohlc::SendOHLCResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetOHLC : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetOHLC() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ohlc::StockRequest, ::ohlc::OHLC>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ohlc::StockRequest, ::ohlc::OHLC>* streamer) {
                       return this->StreamedGetOHLC(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetOHLC() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetOHLC(::grpc::ServerContext* /*context*/, const ::ohlc::StockRequest* /*request*/, ::ohlc::OHLC* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetOHLC(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ohlc::StockRequest,::ohlc::OHLC>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SendOHLC<WithStreamedUnaryMethod_GetOHLC<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SendOHLC<WithStreamedUnaryMethod_GetOHLC<Service > > StreamedService;
};

}  // namespace ohlc


#endif  // GRPC_ohlc_2eproto__INCLUDED
